// Date: 2/2/2013 4:15:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package f4113n.Borderlands2Mod.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSniper extends ModelBase
{
  //fields
    ModelRenderer Handle;
    ModelRenderer Body;
    ModelRenderer Barrel;
    ModelRenderer Scope_Base_Back;
    ModelRenderer Scope_Base_Front;
  
  public ModelSniper()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Handle = new ModelRenderer(this, 0, 32);
      Handle.addBox(-1F, 0F, -1F, 2, 4, 2);
      Handle.setRotationPoint(0F, 20F, 3F);
      Handle.setTextureSize(64, 64);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 0, 14);
      Body.addBox(-1F, -4F, -13F, 2, 4, 14);
      Body.setRotationPoint(0F, 20F, 3F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Barrel = new ModelRenderer(this, 32, 14);
      Barrel.addBox(-0.5F, -3F, -23F, 1, 1, 10);
      Barrel.setRotationPoint(0F, 20F, 3F);
      Barrel.setTextureSize(64, 64);
      Barrel.mirror = true;
      setRotation(Barrel, 0F, 0F, 0F);
      Scope_Base_Back = new ModelRenderer(this, 16, 12);
      Scope_Base_Back.addBox(-1F, -5F, -3F, 2, 1, 1);
      Scope_Base_Back.setRotationPoint(0F, 20F, 3F);
      Scope_Base_Back.setTextureSize(64, 64);
      Scope_Base_Back.mirror = true;
      setRotation(Scope_Base_Back, 0F, 0F, 0F);
      Scope_Base_Front = new ModelRenderer(this, 16, 12);
      Scope_Base_Front.addBox(-1F, -5F, -11F, 2, 1, 1);
      Scope_Base_Front.setRotationPoint(0F, 20F, 3F);
      Scope_Base_Front.setTextureSize(64, 64);
      Scope_Base_Front.mirror = true;
      setRotation(Scope_Base_Front, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    Handle.render(f5);
    Body.render(f5);
    Barrel.render(f5);
    Scope_Base_Back.render(f5);
    Scope_Base_Front.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
	  model.rotateAngleX = x;
	  model.rotateAngleY = 1F;
	  model.rotateAngleZ = 40.8F;
  }
  
  public void render(float scale) {

	  Handle.render(scale);
	  Body.render(scale);
	  Barrel.render(scale);
	  Scope_Base_Back.render(scale);
	  Scope_Base_Front.render(scale);
  }

}
